"""empty message

Revision ID: 9463391f3f76
Revises: 
Create Date: 2023-07-26 10:08:09.191441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9463391f3f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prts_rc_rcinfo',
    sa.Column('primary_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_table('prts_rc_sendmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_key', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prts_rc_sendmessage')
    op.drop_table('prts_rc_rcinfo')
    # ### end Alembic commands ###
